"use client"

import { useState } from "react"
import { Sparkles, Loader2, Copy, Check } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { generateServiceDescription, GenerateServiceDescriptionInput } from "@/ai/flows/generate-service-description-flow"
import { useToast } from "@/hooks/use-toast"
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function AIListingTool() {
  const { toast } = useToast()
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)
  const [formData, setFormData] = useState<GenerateServiceDescriptionInput>({
    serviceName: "",
    category: "Web Development",
    keywords: [],
    targetAudience: "",
    keyFeatures: [],
  })
  const [generatedText, setGeneratedText] = useState("")
  const [keywordInput, setKeywordInput] = useState("")
  const [featureInput, setFeatureInput] = useState("")

  const handleGenerate = async () => {
    if (!formData.serviceName || !formData.targetAudience) {
      toast({
        title: "Missing Information",
        description: "Please fill in the service name and target audience.",
        variant: "destructive"
      })
      return
    }

    setLoading(true)
    try {
      const result = await generateServiceDescription(formData)
      setGeneratedText(result.description)
      toast({
        title: "Success",
        description: "Your description has been generated by S-Tech AI.",
      })
    } catch (error) {
      toast({
        title: "Generation Failed",
        description: "Something went wrong. Please try again.",
        variant: "destructive"
      })
    } finally {
      setLoading(false)
    }
  }

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedText)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
    toast({
      title: "Copied to Clipboard",
      description: "Description ready for use.",
    })
  }

  const addKeyword = () => {
    if (keywordInput.trim()) {
      setFormData(prev => ({ ...prev, keywords: [...prev.keywords, keywordInput.trim()] }))
      setKeywordInput("")
    }
  }

  const addFeature = () => {
    if (featureInput.trim()) {
      setFormData(prev => ({ ...prev, keyFeatures: [...prev.keyFeatures, featureInput.trim()] }))
      setFeatureInput("")
    }
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
      <Card className="border-none shadow-sm">
        <CardHeader>
          <CardTitle className="text-xl font-headline font-bold text-primary flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-accent" /> AI Content Assistant
          </CardTitle>
          <CardDescription>Tell the AI about your new service listing.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-5">
          <div className="space-y-2">
            <Label htmlFor="service-name">Service Name</Label>
            <Input 
              id="service-name" 
              placeholder="e.g. S-Tech Secure Portal" 
              value={formData.serviceName}
              onChange={e => setFormData(prev => ({ ...prev, serviceName: e.target.value }))}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="category">Category</Label>
            <Input 
              id="category" 
              placeholder="e.g. AI Cybersecurity" 
              value={formData.category}
              onChange={e => setFormData(prev => ({ ...prev, category: e.target.value }))}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="audience">Target Audience</Label>
            <Textarea 
              id="audience" 
              placeholder="e.g. Medium-sized enterprises in Zimbabwe looking for robust security..." 
              value={formData.targetAudience}
              onChange={e => setFormData(prev => ({ ...prev, targetAudience: e.target.value }))}
              className="min-h-[80px]"
            />
          </div>
          <div className="space-y-2">
            <Label>Keywords (Press Enter to add)</Label>
            <div className="flex gap-2 mb-2">
              <Input 
                value={keywordInput}
                onKeyDown={e => e.key === 'Enter' && addKeyword()}
                onChange={e => setKeywordInput(e.target.value)}
                placeholder="SEO Keywords"
              />
              <Button type="button" variant="outline" onClick={addKeyword}>Add</Button>
            </div>
            <div className="flex flex-wrap gap-2">
              {formData.keywords.map((k, idx) => (
                <Badge key={idx} variant="secondary" className="bg-primary/5 text-primary">
                  {k}
                </Badge>
              ))}
            </div>
          </div>
          <div className="space-y-2">
            <Label>Key Features</Label>
            <div className="flex gap-2 mb-2">
              <Input 
                value={featureInput}
                onKeyDown={e => e.key === 'Enter' && addFeature()}
                onChange={e => setFeatureInput(e.target.value)}
                placeholder="Benefit or feature"
              />
              <Button type="button" variant="outline" onClick={addFeature}>Add</Button>
            </div>
            <div className="flex flex-wrap gap-2">
              {formData.keyFeatures.map((f, idx) => (
                <Badge key={idx} variant="outline" className="border-accent text-accent">
                  {f}
                </Badge>
              ))}
            </div>
          </div>
          <Button 
            className="w-full bg-accent hover:bg-accent/90 text-white py-6 text-lg font-bold rounded-xl"
            onClick={handleGenerate}
            disabled={loading}
          >
            {loading ? (
              <>
                <Loader2 className="w-5 h-5 mr-2 animate-spin" /> Generating...
              </>
            ) : (
              <>
                <Sparkles className="w-5 h-5 mr-2" /> Generate Compelling Description
              </>
            )}
          </Button>
        </CardContent>
      </Card>

      <Card className="border-none shadow-sm bg-primary/5 border-2 border-dashed border-primary/20">
        <CardHeader className="flex flex-row items-center justify-between space-y-0">
          <div>
            <CardTitle className="text-xl font-headline font-bold text-primary">AI Result</CardTitle>
            <CardDescription>Optimized SEO description will appear here.</CardDescription>
          </div>
          {generatedText && (
            <Button 
              variant="ghost" 
              size="sm" 
              className="text-primary hover:text-accent font-bold"
              onClick={handleCopy}
            >
              {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
              {copied ? "Copied" : "Copy"}
            </Button>
          )}
        </CardHeader>
        <CardContent>
          {!generatedText && !loading && (
            <div className="py-20 flex flex-col items-center justify-center text-center px-6">
              <div className="w-16 h-16 bg-white rounded-full flex items-center justify-center mb-6 shadow-sm">
                <Sparkles className="w-8 h-8 text-muted-foreground opacity-30" />
              </div>
              <p className="text-muted-foreground italic font-light leading-relaxed">
                "Fill out the service details on the left and click generate to see the magic happen. Our AI is trained to write high-converting copy specifically for the Zimbabwean digital market."
              </p>
            </div>
          )}
          
          {loading && (
            <div className="py-20 flex flex-col items-center justify-center">
              <Loader2 className="w-10 h-10 text-accent animate-spin mb-4" />
              <p className="text-primary font-medium">Crafting your professional copy...</p>
            </div>
          )}

          {generatedText && !loading && (
            <div className="prose prose-sm max-w-none text-muted-foreground leading-relaxed whitespace-pre-wrap font-light text-base bg-white p-6 rounded-xl shadow-inner border border-primary/10">
              {generatedText}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}